language: ruby

rvm:
  - 2.6.3

services:
  - docker

before_install:
  - docker build -t portfolio .
  - docker run -d --name portfolio_container portfolio

script:
  - docker exec -t portfolio_container rails test
